name: tag

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      # Create Git tag from package version
      - uses: neverendingqs/gh-action-tag-on-npm-version@master
